#ifndef PROTOCOL__PACKAGE_FACTORY
#define PROTOCOL__PACKAGE_FACTORY
/* This file is generated by lw_protogen. DO NOT EDIT.*/
#include <signal.h>
#include <memory>
#include <Protocol/Streams/DataStream.h>
namespace Protocol{
	class Package;
	class PackageFactory {
		public:
			static std::auto_ptr<Package> deserialize(const sigset_t
					&mask, const bool &cancel, uint8_t id,
					size_t &length, DataStream &stream);
			static std::auto_ptr<Package> deserialize_unknown(const sigset_t
					&mask, const bool &cancel,
					size_t &length, DataStream &stream);
	};
}
#endif /* PROTOCOL__PACKAGE_FACTORY */
