#ifndef PROTOCOL_BAG_PACKAGE_H
#define PROTOCOL_BAG_PACKAGE_H

/* This file is generated by lw_protogen. DO NOT EDIT.*/
#include <string>
#include <memory>
#include <Protocol/Packages/Package.h>
#include <Protocol/Packages/Data/CollectionPackage.h>
#include <Protocol/ByteBuffer.h>

namespace Protocol {
	class BagPackage : public CollectionPackage {
		private:
		public:
			BagPackage(const sigset_t &mask, const bool &cancel, size_t &length, DataStream &stream);
			BagPackage();

			uint8_t get_type() const;
	};
}
#endif
