/* This file is generated by lw_protogen. DO NOT EDIT.*/
#include <string>
#include <sstream>
#include <Protocol/Enums/DataPackages.h>
#include <Protocol/DataPackageFactory.h>
#include <Protocol/Enums/Packages.h>
#include <Protocol/PackageFactory.h>
#include <Protocol/Enums/Packages.h>
#include <Protocol/Packages/Data/BagPackage.h>

using namespace std;

namespace Protocol {
	BagPackage::BagPackage(const sigset_t &mask, const bool &cancel, size_t &length, DataStream &stream)
	{
	}

	BagPackage::BagPackage()
	{
	}

	uint8_t BagPackage::get_type() const
	{
		return BAG_PACKAGE;
	}

}
