#ifndef PROTOCOL_BINDING_PACKAGE_H
#define PROTOCOL_BINDING_PACKAGE_H

/* This file is generated by lw_protogen. DO NOT EDIT.*/
#include <string>
#include <memory>
#include <Protocol/Packages/Package.h>
#include <Protocol/ByteBuffer.h>

namespace Protocol {
	class BindingPackage : public Package {
		private:
			std::auto_ptr<ByteBuffer> bindingName;
			std::auto_ptr<Package> value;
		public:
			BindingPackage(const sigset_t &mask, const bool &cancel, size_t &length, DataStream &stream);
			BindingPackage(std::auto_ptr<ByteBuffer> bindingName, std::auto_ptr<Package> value);

			void serialize(const sigset_t &mask, const bool& cancel, DataStream &stream, bool with_header = true) const;
			uint8_t get_type() const;
			std::string to_string() const;
			size_t get_ser_size() const;
			const ByteBuffer &get_val_bindingName() const;
			const Package &get_val_value() const;
	};
}
#endif
