/* This file is generated by lw_protogen. DO NOT EDIT.*/
#include <string>
#include <sstream>
#include <Protocol/Enums/DataPackages.h>
#include <Protocol/DataPackageFactory.h>
#include <Protocol/Enums/Packages.h>
#include <Protocol/PackageFactory.h>
#include <Protocol/Enums/Packages.h>
#include <Protocol/Packages/Data/BoolPackage.h>

using namespace std;

namespace Protocol {
	BoolPackage::BoolPackage(const sigset_t &mask, const bool &cancel, size_t &length, DataStream &stream):

		value(stream.read_bool(mask, cancel, length))
	{
	}

	BoolPackage::BoolPackage(bool value):

		value(value)
	{
	}

	void BoolPackage::serialize(const sigset_t &mask, const bool& cancel, DataStream &stream, bool with_header) const
	{
		if (with_header){
			stream.write_uint8(mask, cancel, get_type());
			stream.write_uint32(mask, cancel, get_ser_size());
		}
		stream.write_bool(mask, cancel, value);
	}

	uint8_t BoolPackage::get_type() const
	{
		return BOOL_PACKAGE;
	}

	string BoolPackage::to_string() const
	{
		stringstream ss;
		ss << "BoolPackage:" << endl;
		ss << "  value: " << value << endl;
		return ss.str();
	}

	size_t BoolPackage::get_ser_size() const
	{
		return 0 + 1;
	}

	bool BoolPackage::get_val_value() const
	{
		return value;
	}
}
