/* This file is generated by lw_protogen. DO NOT EDIT.*/
#include <string>
#include <sstream>
#include <Protocol/Enums/DataPackages.h>
#include <Protocol/DataPackageFactory.h>
#include <Protocol/Enums/Packages.h>
#include <Protocol/PackageFactory.h>
#include <Protocol/Enums/Packages.h>
#include <Protocol/Packages/Data/CollectionPackage.h>

using namespace std;

namespace Protocol {
	CollectionPackage::CollectionPackage(const sigset_t &mask, const bool &cancel, size_t &length, DataStream &stream)
	{
	}

	CollectionPackage::CollectionPackage()
	{
	}

	void CollectionPackage::serialize(const sigset_t &mask, const bool& cancel, DataStream &stream, bool with_header) const
	{
		if (with_header){
			stream.write_uint8(mask, cancel, get_type());
			stream.write_uint32(mask, cancel, get_ser_size());
		}
	}

	uint8_t CollectionPackage::get_type() const
	{
		return COLLECTION_PACKAGE;
	}

	string CollectionPackage::to_string() const
	{
		stringstream ss;
		ss << "CollectionPackage:" << endl;
		return ss.str();
	}

	size_t CollectionPackage::get_ser_size() const
	{
		return 0;
	}

}
