#ifndef PROTOCOL_DATE_PACKAGE_H
#define PROTOCOL_DATE_PACKAGE_H

/* This file is generated by lw_protogen. DO NOT EDIT.*/
#include <string>
#include <memory>
#include <Protocol/Packages/Package.h>
#include <Protocol/ByteBuffer.h>

namespace Protocol {
	class DatePackage : public Package {
		private:
			int16_t year;
			uint8_t month;
			uint8_t day;
		public:
			DatePackage(const sigset_t &mask, const bool &cancel, size_t &length, DataStream &stream);
			DatePackage(int16_t year, uint8_t month, uint8_t day);

			void serialize(const sigset_t &mask, const bool& cancel, DataStream &stream, bool with_header = true) const;
			uint8_t get_type() const;
			std::string to_string() const;
			size_t get_ser_size() const;
			int16_t get_val_year() const;
			uint8_t get_val_month() const;
			uint8_t get_val_day() const;
	};
}
#endif
