#ifndef PROTOCOL_DATETIMETZ_PACKAGE_H
#define PROTOCOL_DATETIMETZ_PACKAGE_H

/* This file is generated by lw_protogen. DO NOT EDIT.*/
#include <string>
#include <memory>
#include <Protocol/Packages/Package.h>
#include <Protocol/ByteBuffer.h>

namespace Protocol {
	class DatetimetzPackage : public Package {
		private:
			int16_t year;
			uint8_t month;
			uint8_t day;
			uint8_t hour;
			uint8_t minutes;
			uint8_t sec;
			int16_t milis;
			int8_t tz;
		public:
			DatetimetzPackage(const sigset_t &mask, const bool &cancel, size_t &length, DataStream &stream);
			DatetimetzPackage(int16_t year, uint8_t month, uint8_t day, uint8_t hour, uint8_t minutes, uint8_t sec, int16_t milis, int8_t tz);

			void serialize(const sigset_t &mask, const bool& cancel, DataStream &stream, bool with_header = true) const;
			uint8_t get_type() const;
			std::string to_string() const;
			size_t get_ser_size() const;
			int16_t get_val_year() const;
			uint8_t get_val_month() const;
			uint8_t get_val_day() const;
			uint8_t get_val_hour() const;
			uint8_t get_val_minutes() const;
			uint8_t get_val_sec() const;
			int16_t get_val_milis() const;
			int8_t get_val_tz() const;
	};
}
#endif
