#ifndef PROTOCOL_REF_PACKAGE_H
#define PROTOCOL_REF_PACKAGE_H

/* This file is generated by lw_protogen. DO NOT EDIT.*/
#include <string>
#include <memory>
#include <Protocol/Packages/Package.h>
#include <Protocol/ByteBuffer.h>

namespace Protocol {
	class RefPackage : public Package {
		private:
			uint64_t value_id;
		public:
			RefPackage(const sigset_t &mask, const bool &cancel, size_t &length, DataStream &stream);
			RefPackage(uint64_t value_id);

			void serialize(const sigset_t &mask, const bool& cancel, DataStream &stream, bool with_header = true) const;
			uint8_t get_type() const;
			std::string to_string() const;
			size_t get_ser_size() const;
			uint64_t get_val_value_id() const;
	};
}
#endif
