/* This file is generated by lw_protogen. DO NOT EDIT.*/
#include <string>
#include <sstream>
#include <Protocol/Enums/DataPackages.h>
#include <Protocol/DataPackageFactory.h>
#include <Protocol/Enums/Packages.h>
#include <Protocol/PackageFactory.h>
#include <Protocol/Enums/Packages.h>
#include <Protocol/Packages/Data/SequencePackage.h>

using namespace std;

namespace Protocol {
	SequencePackage::SequencePackage(const sigset_t &mask, const bool &cancel, size_t &length, DataStream &stream)
	{
	}

	SequencePackage::SequencePackage()
	{
	}

	uint8_t SequencePackage::get_type() const
	{
		return SEQUENCE_PACKAGE;
	}

}
