/* This file is generated by lw_protogen. DO NOT EDIT.*/
#include <string>
#include <sstream>
#include <Protocol/Enums/DataPackages.h>
#include <Protocol/DataPackageFactory.h>
#include <Protocol/Enums/Packages.h>
#include <Protocol/PackageFactory.h>
#include <Protocol/Enums/Packages.h>
#include <Protocol/Packages/Data/Sint8Package.h>

using namespace std;

namespace Protocol {
	Sint8Package::Sint8Package(const sigset_t &mask, const bool &cancel, size_t &length, DataStream &stream):

		value(stream.read_int8(mask, cancel, length))
	{
	}

	Sint8Package::Sint8Package(int8_t value):

		value(value)
	{
	}

	void Sint8Package::serialize(const sigset_t &mask, const bool& cancel, DataStream &stream, bool with_header) const
	{
		if (with_header){
			stream.write_uint8(mask, cancel, get_type());
			stream.write_uint32(mask, cancel, get_ser_size());
		}
		stream.write_int8(mask, cancel, value);
	}

	uint8_t Sint8Package::get_type() const
	{
		return SINT8_PACKAGE;
	}

	string Sint8Package::to_string() const
	{
		stringstream ss;
		ss << "Sint8Package:" << endl;
		ss << "  value: " << ((int)value) << endl;
		return ss.str();
	}

	size_t Sint8Package::get_ser_size() const
	{
		return 0 + 1;
	}

	int8_t Sint8Package::get_val_value() const
	{
		return value;
	}
}
