#ifndef PROTOCOL_STRUCT_PACKAGE_H
#define PROTOCOL_STRUCT_PACKAGE_H

/* This file is generated by lw_protogen. DO NOT EDIT.*/
#include <string>
#include <memory>
#include <Protocol/Packages/Package.h>
#include <Protocol/Packages/Data/CollectionPackage.h>
#include <Protocol/ByteBuffer.h>

namespace Protocol {
	class StructPackage : public CollectionPackage {
		private:
		public:
			StructPackage(const sigset_t &mask, const bool &cancel, size_t &length, DataStream &stream);
			StructPackage();

			uint8_t get_type() const;
	};
}
#endif
