/* This file is generated by lw_protogen. DO NOT EDIT.*/
#include <string>
#include <sstream>
#include <Protocol/Enums/DataPackages.h>
#include <Protocol/DataPackageFactory.h>
#include <Protocol/Enums/Packages.h>
#include <Protocol/PackageFactory.h>
#include <Protocol/Enums/Packages.h>
#include <Protocol/Packages/Data/TimetzPackage.h>

using namespace std;

namespace Protocol {
	TimetzPackage::TimetzPackage(const sigset_t &mask, const bool &cancel, size_t &length, DataStream &stream):

		hour(stream.read_uint8(mask, cancel, length)),
		minuts(stream.read_uint8(mask, cancel, length)),
		sec(stream.read_uint8(mask, cancel, length)),
		milis(stream.read_int16(mask, cancel, length)),
		tz(stream.read_int8(mask, cancel, length))
	{
	}

	TimetzPackage::TimetzPackage(uint8_t hour, uint8_t minuts, uint8_t sec, int16_t milis, int8_t tz):

		hour(hour),
		minuts(minuts),
		sec(sec),
		milis(milis),
		tz(tz)
	{
	}

	void TimetzPackage::serialize(const sigset_t &mask, const bool& cancel, DataStream &stream, bool with_header) const
	{
		if (with_header){
			stream.write_uint8(mask, cancel, get_type());
			stream.write_uint32(mask, cancel, get_ser_size());
		}
		stream.write_uint8(mask, cancel, hour);
		stream.write_uint8(mask, cancel, minuts);
		stream.write_uint8(mask, cancel, sec);
		stream.write_int16(mask, cancel, milis);
		stream.write_int8(mask, cancel, tz);
	}

	uint8_t TimetzPackage::get_type() const
	{
		return TIMETZ_PACKAGE;
	}

	string TimetzPackage::to_string() const
	{
		stringstream ss;
		ss << "TimetzPackage:" << endl;
		ss << "  hour: " << ((int)hour) << endl;
		ss << "  minuts: " << ((int)minuts) << endl;
		ss << "  sec: " << ((int)sec) << endl;
		ss << "  milis: " << milis << endl;
		ss << "  tz: " << ((int)tz) << endl;
		return ss.str();
	}

	size_t TimetzPackage::get_ser_size() const
	{
		return 0 + 1 + 1 + 1 + 2 + 1;
	}

	uint8_t TimetzPackage::get_val_hour() const
	{
		return hour;
	}
	uint8_t TimetzPackage::get_val_minuts() const
	{
		return minuts;
	}
	uint8_t TimetzPackage::get_val_sec() const
	{
		return sec;
	}
	int16_t TimetzPackage::get_val_milis() const
	{
		return milis;
	}
	int8_t TimetzPackage::get_val_tz() const
	{
		return tz;
	}
}
