#ifndef PROTOCOL_UINT32_PACKAGE_H
#define PROTOCOL_UINT32_PACKAGE_H

/* This file is generated by lw_protogen. DO NOT EDIT.*/
#include <string>
#include <memory>
#include <Protocol/Packages/Package.h>
#include <Protocol/ByteBuffer.h>

namespace Protocol {
	class Uint32Package : public Package {
		private:
			uint32_t value;
		public:
			Uint32Package(const sigset_t &mask, const bool &cancel, size_t &length, DataStream &stream);
			Uint32Package(uint32_t value);

			void serialize(const sigset_t &mask, const bool& cancel, DataStream &stream, bool with_header = true) const;
			uint8_t get_type() const;
			std::string to_string() const;
			size_t get_ser_size() const;
			uint32_t get_val_value() const;
	};
}
#endif
