/* This file is generated by lw_protogen. DO NOT EDIT.*/
#include <string>
#include <sstream>
#include <Protocol/Enums/DataPackages.h>
#include <Protocol/DataPackageFactory.h>
#include <Protocol/Enums/Packages.h>
#include <Protocol/PackageFactory.h>
#include <Protocol/Enums/Packages.h>
#include <Protocol/Packages/Data/Uint16Package.h>

using namespace std;

namespace Protocol {
	Uint16Package::Uint16Package(const sigset_t &mask, const bool &cancel, size_t &length, DataStream &stream):

		value(stream.read_uint16(mask, cancel, length))
	{
	}

	Uint16Package::Uint16Package(uint16_t value):

		value(value)
	{
	}

	void Uint16Package::serialize(const sigset_t &mask, const bool& cancel, DataStream &stream, bool with_header) const
	{
		if (with_header){
			stream.write_uint8(mask, cancel, get_type());
			stream.write_uint32(mask, cancel, get_ser_size());
		}
		stream.write_uint16(mask, cancel, value);
	}

	uint8_t Uint16Package::get_type() const
	{
		return UINT16_PACKAGE;
	}

	string Uint16Package::to_string() const
	{
		stringstream ss;
		ss << "Uint16Package:" << endl;
		ss << "  value: " << value << endl;
		return ss.str();
	}

	size_t Uint16Package::get_ser_size() const
	{
		return 0 + 2;
	}

	uint16_t Uint16Package::get_val_value() const
	{
		return value;
	}
}
