#ifndef PROTOCOL_A_SC_SETOPT_PACKAGE_H
#define PROTOCOL_A_SC_SETOPT_PACKAGE_H

/* This file is generated by lw_protogen. DO NOT EDIT.*/
#include <string>
#include <memory>
#include <Protocol/Packages/Package.h>
#include <Protocol/ByteBuffer.h>

namespace Protocol {
	class AScSetoptPackage : public Package {
		private:
			std::auto_ptr<ByteBuffer> key;
			std::auto_ptr<ByteBuffer> value;
		public:
			AScSetoptPackage(const sigset_t &mask, const bool &cancel, size_t &length, DataStream &stream);
			AScSetoptPackage(std::auto_ptr<ByteBuffer> key, std::auto_ptr<ByteBuffer> value);

			void serialize(const sigset_t &mask, const bool& cancel, DataStream &stream, bool with_header = true) const;
			uint8_t get_type() const;
			std::string to_string() const;
			size_t get_ser_size() const;
			const ByteBuffer &get_val_key() const;
			const ByteBuffer &get_val_value() const;
	};
}
#endif
