/* This file is generated by lw_protogen. DO NOT EDIT.*/
#include <string>
#include <sstream>
#include <Protocol/Enums/DataPackages.h>
#include <Protocol/DataPackageFactory.h>
#include <Protocol/Enums/Packages.h>
#include <Protocol/PackageFactory.h>
#include <Protocol/Enums/Packages.h>
#include <Protocol/Packages/QCExecutePackage.h>

using namespace std;

namespace Protocol {
	QCExecutePackage::QCExecutePackage(const sigset_t &mask, const bool &cancel, size_t &length, DataStream &stream):


		statement_id(stream.read_uint64(mask, cancel, length)),
		flags(stream.read_uint64(mask, cancel, length))
	{
	}

	QCExecutePackage::QCExecutePackage(uint64_t statement_id, uint64_t flags):

		statement_id(statement_id),
		flags(flags)
	{
	}

	void QCExecutePackage::serialize(const sigset_t &mask, const bool& cancel, DataStream &stream, bool with_header) const
	{
		if (with_header){
			stream.write_uint8(mask, cancel, get_type());
			stream.write_uint32(mask, cancel, get_ser_size());
		}
		stream.write_uint64(mask, cancel, statement_id);
		stream.write_uint64(mask, cancel, flags);
	}

	uint8_t QCExecutePackage::get_type() const
	{
		return Q_C_EXECUTE_PACKAGE;
	}

	string QCExecutePackage::to_string() const
	{
		stringstream ss;
		ss << "QCExecutePackage:" << endl;
		ss << "  statement_id: " << statement_id << endl;
		ss << "  flags: " << flags << endl;
		return ss.str();
	}

	size_t QCExecutePackage::get_ser_size() const
	{
		return 0 + 8 + 8;
	}

	uint64_t QCExecutePackage::get_val_statement_id() const
	{
		return statement_id;
	}
	uint64_t QCExecutePackage::get_val_flags() const
	{
		return flags;
	}
}
