#ifndef PROTOCOL_Q_C_STATEMENT_PACKAGE_H
#define PROTOCOL_Q_C_STATEMENT_PACKAGE_H

/* This file is generated by lw_protogen. DO NOT EDIT.*/
#include <string>
#include <memory>
#include <Protocol/Packages/Package.h>
#include <Protocol/ByteBuffer.h>

namespace Protocol {
	class QCStatementPackage : public Package {
		private:
			uint64_t flags;
			std::auto_ptr<ByteBuffer> statement;
		public:
			QCStatementPackage(const sigset_t &mask, const bool &cancel, size_t &length, DataStream &stream);
			QCStatementPackage(uint64_t flags, std::auto_ptr<ByteBuffer> statement);

			void serialize(const sigset_t &mask, const bool& cancel, DataStream &stream, bool with_header = true) const;
			uint8_t get_type() const;
			std::string to_string() const;
			size_t get_ser_size() const;
			uint64_t get_val_flags() const;
			const ByteBuffer &get_val_statement() const;
	};
}
#endif
