#ifndef PROTOCOL_Q_S_EXECUTION_FINISHED_PACKAGE_H
#define PROTOCOL_Q_S_EXECUTION_FINISHED_PACKAGE_H

/* This file is generated by lw_protogen. DO NOT EDIT.*/
#include <string>
#include <memory>
#include <Protocol/Packages/Package.h>
#include <Protocol/ByteBuffer.h>

namespace Protocol {
	class QSExecutionFinishedPackage : public Package {
		private:
			VarUint mod_atom_pointer_cnt;
			VarUint del_cnt;
			VarUint new_roots_cnt;
			VarUint inserts_cnt;
		public:
			QSExecutionFinishedPackage(const sigset_t &mask, const bool &cancel, size_t &length, DataStream &stream);
			QSExecutionFinishedPackage(VarUint mod_atom_pointer_cnt, VarUint del_cnt, VarUint new_roots_cnt, VarUint inserts_cnt);

			void serialize(const sigset_t &mask, const bool& cancel, DataStream &stream, bool with_header = true) const;
			uint8_t get_type() const;
			std::string to_string() const;
			size_t get_ser_size() const;
			VarUint get_val_mod_atom_pointer_cnt() const;
			VarUint get_val_del_cnt() const;
			VarUint get_val_new_roots_cnt() const;
			VarUint get_val_inserts_cnt() const;
	};
}
#endif
