#ifndef PROTOCOL_V_SC_ABORT_PACKAGE_H
#define PROTOCOL_V_SC_ABORT_PACKAGE_H

/* This file is generated by lw_protogen. DO NOT EDIT.*/
#include <string>
#include <memory>
#include <Protocol/Packages/Package.h>
#include <Protocol/ByteBuffer.h>

namespace Protocol {
	class VSCAbortPackage : public Package {
		private:
			uint32_t reason_code;
			std::auto_ptr<ByteBuffer> reason_string;
		public:
			VSCAbortPackage(const sigset_t &mask, const bool &cancel, size_t &length, DataStream &stream);
			VSCAbortPackage(uint32_t reason_code, std::auto_ptr<ByteBuffer> reason_string);

			void serialize(const sigset_t &mask, const bool& cancel, DataStream &stream, bool with_header = true) const;
			uint8_t get_type() const;
			std::string to_string() const;
			size_t get_ser_size() const;
			uint32_t get_val_reason_code() const;
			const ByteBuffer &get_val_reason_string() const;
	};
}
#endif
