/* This file is generated by lw_protogen. DO NOT EDIT.*/
#include <string>
#include <sstream>
#include <Protocol/Enums/DataPackages.h>
#include <Protocol/DataPackageFactory.h>
#include <Protocol/Enums/Packages.h>
#include <Protocol/PackageFactory.h>
#include <Protocol/Enums/Packages.h>
#include <Protocol/Packages/VSCAbortPackage.h>

using namespace std;

namespace Protocol {
	VSCAbortPackage::VSCAbortPackage(const sigset_t &mask, const bool &cancel, size_t &length, DataStream &stream):

		reason_code(stream.read_uint32(mask, cancel, length)),
		reason_string(stream.read_string(mask, cancel, length))
	{
	}

	VSCAbortPackage::VSCAbortPackage(uint32_t reason_code, std::auto_ptr<ByteBuffer> reason_string):

		reason_code(reason_code),
		reason_string(reason_string)
	{
	}

	void VSCAbortPackage::serialize(const sigset_t &mask, const bool& cancel, DataStream &stream, bool with_header) const
	{
		if (with_header){
			stream.write_uint8(mask, cancel, get_type());
			stream.write_uint32(mask, cancel, get_ser_size());
		}
		stream.write_uint32(mask, cancel, reason_code);
		stream.write_string(mask, cancel, reason_string);
	}

	uint8_t VSCAbortPackage::get_type() const
	{
		return V_SC_ABORT_PACKAGE;
	}

	string VSCAbortPackage::to_string() const
	{
		stringstream ss;
		ss << "VSCAbortPackage:" << endl;
		ss << "  reason_code: " << reason_code << endl;
		ss << "  reason_string: " << reason_string->get_const_data() << endl;
		return ss.str();
	}

	size_t VSCAbortPackage::get_ser_size() const
	{
		return 0 + 4 + reason_string->get_ser_size();
	}

	uint32_t VSCAbortPackage::get_val_reason_code() const
	{
		return reason_code;
	}
	const ByteBuffer &VSCAbortPackage::get_val_reason_string() const
	{
		return *reason_string.get();
	}
}
