/* This file is generated by lw_protogen. DO NOT EDIT.*/
#include <string>
#include <sstream>
#include <Protocol/Enums/DataPackages.h>
#include <Protocol/DataPackageFactory.h>
#include <Protocol/Enums/Packages.h>
#include <Protocol/PackageFactory.h>
#include <Protocol/Enums/Packages.h>
#include <Protocol/Packages/VSCFinishedPackage.h>

using namespace std;

namespace Protocol {
	VSCFinishedPackage::VSCFinishedPackage(const sigset_t &mask, const bool &cancel, size_t &length, DataStream &stream)

	{
	}

	VSCFinishedPackage::VSCFinishedPackage()
	{
	}

	void VSCFinishedPackage::serialize(const sigset_t &mask, const bool& cancel, DataStream &stream, bool with_header) const
	{
		if (with_header){
			stream.write_uint8(mask, cancel, get_type());
			stream.write_uint32(mask, cancel, get_ser_size());
		}
	}

	uint8_t VSCFinishedPackage::get_type() const
	{
		return V_SC_FINISHED_PACKAGE;
	}

	string VSCFinishedPackage::to_string() const
	{
		stringstream ss;
		ss << "VSCFinishedPackage:" << endl;
		return ss.str();
	}

	size_t VSCFinishedPackage::get_ser_size() const
	{
		return 0;
	}

}
