#ifndef PROTOCOL_V_SC_FINISHED_PACKAGE_H
#define PROTOCOL_V_SC_FINISHED_PACKAGE_H

/* This file is generated by lw_protogen. DO NOT EDIT.*/
#include <string>
#include <memory>
#include <Protocol/Packages/Package.h>
#include <Protocol/ByteBuffer.h>

namespace Protocol {
	class VSCFinishedPackage : public Package {
		private:
		public:
			VSCFinishedPackage(const sigset_t &mask, const bool &cancel, size_t &length, DataStream &stream);
			VSCFinishedPackage();

			void serialize(const sigset_t &mask, const bool& cancel, DataStream &stream, bool with_header = true) const;
			uint8_t get_type() const;
			std::string to_string() const;
			size_t get_ser_size() const;
	};
}
#endif
