#ifndef PROTOCOL_V_SC_SENDVALUES_PACKAGE_H
#define PROTOCOL_V_SC_SENDVALUES_PACKAGE_H

/* This file is generated by lw_protogen. DO NOT EDIT.*/
#include <string>
#include <memory>
#include <Protocol/Packages/Package.h>
#include <Protocol/ByteBuffer.h>

namespace Protocol {
	class VScSendvaluesPackage : public Package {
		private:
			VarUint rootValueId;
			VarUint oBundlesCount;
			VarUint oBidCount;
			VarUint pVidCount;
		public:
			VScSendvaluesPackage(const sigset_t &mask, const bool &cancel, size_t &length, DataStream &stream);
			VScSendvaluesPackage(VarUint rootValueId, VarUint oBundlesCount, VarUint oBidCount, VarUint pVidCount);

			void serialize(const sigset_t &mask, const bool& cancel, DataStream &stream, bool with_header = true) const;
			uint8_t get_type() const;
			std::string to_string() const;
			size_t get_ser_size() const;
			VarUint get_val_rootValueId() const;
			VarUint get_val_oBundlesCount() const;
			VarUint get_val_oBidCount() const;
			VarUint get_val_pVidCount() const;
	};
}
#endif
