#ifndef PROTOCOL_V_SC_SENDVALUE_PACKAGE_H
#define PROTOCOL_V_SC_SENDVALUE_PACKAGE_H

/* This file is generated by lw_protogen. DO NOT EDIT.*/
#include <string>
#include <memory>
#include <Protocol/Packages/Package.h>
#include <Protocol/ByteBuffer.h>

namespace Protocol {
	class VSCSendvaluePackage : public Package {
		private:
			VarUint value_id;
			uint8_t flags;
			std::auto_ptr<Package> data;
		public:
			VSCSendvaluePackage(const sigset_t &mask, const bool &cancel, size_t &length, DataStream &stream);
			VSCSendvaluePackage(VarUint value_id, uint8_t flags, std::auto_ptr<Package> data);

			void serialize(const sigset_t &mask, const bool& cancel, DataStream &stream, bool with_header = true) const;
			uint8_t get_type() const;
			std::string to_string() const;
			size_t get_ser_size() const;
			VarUint get_val_value_id() const;
			uint8_t get_val_flags() const;
			const Package &get_val_data() const;
	};
}
#endif
