#ifndef PROTOCOL_W_C_LOGIN_PACKAGE_H
#define PROTOCOL_W_C_LOGIN_PACKAGE_H

/* This file is generated by lw_protogen. DO NOT EDIT.*/
#include <string>
#include <memory>
#include <Protocol/Packages/Package.h>
#include <Protocol/ByteBuffer.h>

namespace Protocol {
	class WCLoginPackage : public Package {
		private:
			uint64_t auth_method;
		public:
			WCLoginPackage(const sigset_t &mask, const bool &cancel, size_t &length, DataStream &stream);
			WCLoginPackage(uint64_t auth_method);

			void serialize(const sigset_t &mask, const bool& cancel, DataStream &stream, bool with_header = true) const;
			uint8_t get_type() const;
			std::string to_string() const;
			size_t get_ser_size() const;
			uint64_t get_val_auth_method() const;
	};
}
#endif
