#ifndef PROTOCOL_W_C_PASSWORD_PACKAGE_H
#define PROTOCOL_W_C_PASSWORD_PACKAGE_H

/* This file is generated by lw_protogen. DO NOT EDIT.*/
#include <string>
#include <memory>
#include <Protocol/Packages/Package.h>
#include <Protocol/ByteBuffer.h>

namespace Protocol {
	class WCPasswordPackage : public Package {
		private:
			std::auto_ptr<ByteBuffer> login;
			std::auto_ptr<ByteBuffer> password;
		public:
			WCPasswordPackage(const sigset_t &mask, const bool &cancel, size_t &length, DataStream &stream);
			WCPasswordPackage(std::auto_ptr<ByteBuffer> login, std::auto_ptr<ByteBuffer> password);

			void serialize(const sigset_t &mask, const bool& cancel, DataStream &stream, bool with_header = true) const;
			uint8_t get_type() const;
			std::string to_string() const;
			size_t get_ser_size() const;
			const ByteBuffer &get_val_login() const;
			const ByteBuffer &get_val_password() const;
	};
}
#endif
