#ifndef PROTOCOL_AUTH_METHODS_H
#define PROTOCOL_AUTH_METHODS_H
/* This file is generated by lw_protogen. DO NOT EDIT.*/

namespace Protocol {
	enum AuthMethods {
		AM_TRUST = 0x0001
	};
}
#endif /*PROTOCOL_AUTH_METHODS_H*/
