#ifndef PROTOCOL_BYE_REASONS_H
#define PROTOCOL_BYE_REASONS_H
/* This file is generated by lw_protogen. DO NOT EDIT.*/

namespace Protocol {
	enum ByeReasons {
		BR_REASON1 = 0x0001
	};
}
#endif /*PROTOCOL_BYE_REASONS_H*/
