#ifndef PROTOCOL_COLLATIONS_H
#define PROTOCOL_COLLATIONS_H
/* This file is generated by lw_protogen. DO NOT EDIT.*/

namespace Protocol {
	enum Collations {
		COLL_DEFAULT = 0,
		COLL_UNICODE_COLLATION_ALGHORITHM_UTS10 = 1
	};
}
#endif /*PROTOCOL_COLLATIONS_H*/
