#ifndef PROTOCOL_ENUMS_H
#define PROTOCOL_ENUMS_H

/* This file is generated by lw_protogen. DO NOT EDIT.*/

#include <Protocol/Enums/Features.h>
#include <Protocol/Enums/AuthMethods.h>
#include <Protocol/Enums/Collations.h>
#include <Protocol/Enums/Modes.h>
#include <Protocol/Enums/StatementFlags.h>
#include <Protocol/Enums/Errors.h>
#include <Protocol/Enums/ByeReasons.h>
#include <Protocol/Enums/SendValueFlags.h>
#include <Protocol/Enums/AbortReasonCodes.h>
#include <Protocol/Enums/DataPackages.h>

#include <Protocol/Enums/Packages.h>

#endif /* PROTOCOL_PACKAGES_H */
