#ifndef PROTOCOL_ERRORS_H
#define PROTOCOL_ERRORS_H
/* This file is generated by lw_protogen. DO NOT EDIT.*/

namespace Protocol {
	enum Errors {
		ERROR_INTERNAL = 0x0000,
		ERROR_PARAMS_INCOMPLETE = 0x0001,
		ERROR_NO_SUCH_VALUE_ID = 0x0002,
		ERROR_OPERATION_NOT_PERMITED = 0x0003
	};
}
#endif /*PROTOCOL_ERRORS_H*/
