#ifndef PROTOCOL_FEATURES_H
#define PROTOCOL_FEATURES_H
/* This file is generated by lw_protogen. DO NOT EDIT.*/

namespace Protocol {
	enum Features {
		F_SSL = 0x0001,
		F_O_SSL = 0x0002,
		F_ZLIB = 0x0004,
		F_AUTOCOMMIT = 0x0010,
		F_OPTIMIZATION = 0x0020
	};
}
#endif /*PROTOCOL_FEATURES_H*/
