#ifndef PROTOCOL_MODES_H
#define PROTOCOL_MODES_H
/* This file is generated by lw_protogen. DO NOT EDIT.*/

namespace Protocol {
	enum Modes {
		MODE_SSL = 1,
		MODE_ZLIB = 2
	};
}
#endif /*PROTOCOL_MODES_H*/
