#ifndef PROTOCOL_SEND_VALUE_FLAGS_H
#define PROTOCOL_SEND_VALUE_FLAGS_H
/* This file is generated by lw_protogen. DO NOT EDIT.*/

namespace Protocol {
	enum SendValueFlags {
		SVF_TO_BE_CONTINUED = 0x01
	};
}
#endif /*PROTOCOL_SEND_VALUE_FLAGS_H*/
