#ifndef PROTOCOL_STATEMENT_FLAGS_H
#define PROTOCOL_STATEMENT_FLAGS_H
/* This file is generated by lw_protogen. DO NOT EDIT.*/

namespace Protocol {
	enum StatementFlags {
		SF_EXECUTE = 0x0001,
		SF_READONLY = 0x0002,
		SF_PREFER_DFS = 0x0010,
		SF_PREFER_BSF = 0x0020
	};
}
#endif /*PROTOCOL_STATEMENT_FLAGS_H*/
