WARNING = "!!! WARNING: This is a make-to-maven2 port. You should use Maven 2 instead !!!"

all:
	@echo $(WARNING)
	mvn package
	@echo $(WARNING)
	

clean:
	@echo $(WARNING)
	mvn clean
	@echo $(WARNING)
